### ISSUE TITLE
角色菜单没有显示

### ISSUE THREAD

**Issue by jpyeah** [jianyan74/rageframe2#15]
我创建了一个角色，然后我给角色分配了一些权限，但是，我用角色账户登录的时候，没有菜单显示，导航菜单也没有显示，请问我要怎么设置呢

**Comment by jianyan74** [comment]
菜单即权限，注意菜单路由要=权限路由才可显示

**Comment by jianyan74** [comment]
最新版本的有此bug，已经修复，请直接更新使用
