### ISSUE TITLE
PHP 7.2 以上版本 yii migrate/backup 报 Cannot use yii\base\Object as Object because 'Object' is a special class name 错误

### ISSUE THREAD

**Issue by philspacey** [jianyan74/rageframe2#3]
PHP 7.2 以上版本 Object 为关键词，在使用 yii migrate/backup 时会报错，需要修改yii2-console-migration/components 底下的两个文件引用的 Object 都改成 BaseObject

**Comment by jianyan74** [comment]
这个是引入的扩展 我对扩展提个issue，可以利用Yii2的classMap进行临时替换原文件

**Comment by jianyan74** [comment]
修改composer.json 里面 "e282486518/yii2-console-migration": "@dev" 然后执行composer update 即可

**Comment by philspacey** [comment]
好的，谢谢简言
