### ISSUE TITLE
用 yii mirgrate/backup 备份，生成文件名不是北京时间问题

### ISSUE THREAD

**Issue by philspacey** [jianyan74/rageframe2#4]
用 yii mirgrate/backup 备份，备份的文件名是 GMT/UTC 的时间，考虑到用 RF 的绝大部分为国内用户，是否考虑将 MigrateCreate.php 66行 gmdate('ymd_His') 换成 gmdate('ymd_His', time() + 3600 * 8)

**Comment by jianyan74** [comment]
这个是扩展的，也不好动，如果有需要可以通过Yii的classMap进行类重写替换
