### ISSUE TITLE
用gii生成model和CRUD碰到的几个坑

### ISSUE THREAD

**Issue by gfbts** [jianyan74/rageframe2#45]
gii可以正常生成文件，但是访问的时候会报错

1、主键名称必须是“id”，其他的比如“xxx_id”会报错；
2、表里面必须包含字段“status”，否则需要改index视图文件；
3、`common/components/Curd.php#161`里面有一个查询条件`andFilterWhere(['merchant_id' => $this->getMerchantId()])`，不太懂加这个判断条件的作用是什么。

**Comment by gfbts** [comment]
再补充一点，生成的控制器必须继承`BaseController`不然会报错

**Comment by jianyan74** [comment]
`andFilterWhere(['merchant_id' => $this->getMerchantId()])` 这个是由于系统支持多商户添加关联字段可要可不要，因为系统封装了curd和一些常规方法所以 必须继承 BaseController，关于id和status则是rageframe的数据库字段规范需要去遵循
