### ISSUE TITLE
[BUG]当POST API请求中不带数据时, 无法在后台->全局日志中查看详情 .

### ISSUE THREAD

**Issue by pengchengzhang** [jianyan74/rageframe2#52]
![image](https://user-images.githubusercontent.com/13394882/70406350-61a93480-1a7b-11ea-8735-0b80a206f66a.png)
问题发现版本: 2.0.27
分析:问题应该在最新版本中也存在，如果post请求的数据为空, 则打不开 后台->全局日志中查看详情

**Comment by jianyan74** [comment]
我再去加个过滤判断
