### ISSUE TITLE
php ./yii migrate/up出错

### ISSUE THREAD

**Issue by heheiscool** [jianyan74/rageframe2#6]
$ php ./yii migrate/up
Unknown command: migrate\up

Did you mean one of these?
    - migrate/up
    - migrate/to
是啥问题？

**Comment by heheiscool** [comment]
应该是$ php ./yii migrate 吧？后面的up是何意？

**Comment by heheiscool** [comment]
php ./yii password/init  这个也报错，有没有其他命令

**Comment by jianyan74** [comment]
确保自己的扩展依赖都安装成功了
