### ISSUE TITLE
gii无法访问，404没有权限访问

### ISSUE THREAD

**Issue by zjljm7880** [jianyan74/rageframe2#64]
平台：macbook
软件与版本：mamp pro 5 (apahe2.4.41    mysql5.7.23  php7.2.8
系统版本：rageframe 2.5.36

新建了数据库，想通过gii添加模型和控制器，地址localhost/backend/gii，提示404，You are not allowed to access this page.在backend/config/params.php里的noAuthRoute中加入了/gii，但没有解决，查看了文档，没有相关说明。

**Comment by jianyan74** [comment]
这个属于Yii2的基础知识，不会在文档上面体现，出现这个情况有2个解决方式
1、检查自己是不是使用了生产模式，如果是生产模式切换为开发模式 php init 那边选择0
2、去backend/config/params-local.php 里面改下授权，把你自己的ip加入进去
