### ISSUE TITLE
在你这个微信开发到底是在后台配置参数还是在配置文件里配置

### ISSUE THREAD

**Issue by codetown** [jianyan74/rageframe2#7]
1.在你这个微信开发到底是在后台配置参数还是在配置文件里配置?
2.代码有点凌乱，搞个微信开发，各种问题层出不穷，session是用_wechatUser获取微信用户参数，还是wechatUser?
3.你这边微信这个你自己试过了么，如果你自己都没有把握，那我还是不用你这个项目了，我找其他项目做微信开发

**Comment by codetown** [comment]
如果微信这块不建议用在生产环境，请标出来哦！

**Comment by jianyan74** [comment]
1、都可以配置，文件配置优先级大于后台配置
2、系统提供了多个获取用户信息的方式，按照自己的喜好使用
3、已经用于多个线上项目，且用的扩展在easywechat官方推荐中
4、系统所有的东西都可用于生产环境
其他：建议你不要用这个系统

**Comment by jianyan74** [comment]
文档那么详细都不看，真不建议你用

**Comment by codetown** [comment]
> 文档那么详细都不看，真不建议你用

好吧是我说话太冲，我道歉，不过你代码里面有很多判空操作没处理好

**Comment by jianyan74** [comment]
> 
> 
> > 文档那么详细都不看，真不建议你用
> 
> 好吧是我说话太冲，我道歉，不过你代码里面有很多判空操作没处理好

比如？你可以直接贴代码

**Comment by codetown** [comment]
> > > 文档那么详细都不看，真不建议你用
> > 
> > 
> > 好吧是我说话太冲，我道歉，不过你代码里面有很多判空操作没处理好
> 
> 比如？你可以直接贴代码
common\components\WechatLoginTrait.php文件下
if (in_array('snsapi_base', Yii::$app->params['wechatConfig']['oauth']['scopes'])) 
{
            return false;
}
如果Yii::$app->params['wechatConfig']['oauth']['scopes']不是数组，或者为空，yii就会报错
我昨天调试代码，到这边报错，我才发现这个问题的。其他地方也有类似的

**Comment by jianyan74** [comment]
> 
> 
> > > > 文档那么详细都不看，真不建议你用
> > > 
> > > 
> > > 好吧是我说话太冲，我道歉，不过你代码里面有很多判空操作没处理好
> > 
> > 
> > 比如？你可以直接贴代码
> > common\components\WechatLoginTrait.php文件下
> > if (in_array('snsapi_base', Yii::$app->params['wechatConfig']['oauth']['scopes']))
> > {
> > return false;
> > }
> > 如果Yii::$app->params['wechatConfig']['oauth']['scopes']不是数组，或者为空，yii就会报错
> > 我昨天调试代码，到这边报错，我才发现这个问题的。其他地方也有类似的

正常是不会报错的，因为在启动的时候已经自动赋值了该变量，除非你自己又去重新改动了这个变量，你自己可以在框架启动的时候直接打印Yii::$app->params['wechatConfig']，不要去重新赋值

**Comment by dlsyaim** [comment]
川哥还是这么固执。。。

**Comment by codetown** [comment]
> 川哥还是这么固执。。。
不想理你，你自己别不识趣好吧
