### ISSUE TITLE
很赞,有些部分可以借鉴下fastadmin把细节优化的更好

### ISSUE THREAD

**Issue by gitzwt** [jianyan74/rageframe2#78]

**Comment by jianyan74** [comment]
比如? 可以具体提一下，我这边做针对性的优化

**Comment by gitzwt** [comment]
功能性的比如命令一件创建curd及页面的列表和form表单,以及后续的插件生态

**Comment by jianyan74** [comment]
这个有的，表单控件都可以让你选择什么控件，这个是可视化的哦

**Comment by jianyan74** [comment]
https://github.com/jianyan74/rageframe2/blob/master/docs/guide-zh-CN/sys-gii.md

**Comment by jianyan74** [comment]
创建好表直接可视化操作，不用写一行代码就可以完成一个curd

**Comment by gitzwt** [comment]
哦,看到了直接使用gii这也很好,谢谢开源

**Comment by jianyan74** [comment]
关于插件生态这部分，其实很多被fastadmin当做插件的功能，rageframe已经内置了，你可以对比下表单控件和已有的插件，不需要下载安装
