### ISSUE TITLE
[v2.2.32] php ./yii migrate/up 插件应用字段缺少默认值

### ISSUE THREAD

**Issue by iCharlesC** [jianyan74/rageframe2#8]
(刚接触这个框架，觉得很不错。加油！)

问题描述：
后台打开“内容管理”，添加新文章，保存后保存，提示缺少view字段默认值。

重现步骤：
1. 本地环境 win10 + wampserver默认配置 php7.2.14 + mysql 5.7.24 （默认InnoDB） + Apache2.4.37，根据安装指引文档配置好
2. 根据安装指引全新安装v2.2.32，全称无错误
3. 登录RF后台---》“应用中心”---》"内容管理"--》"文章管理“---》“创建”按钮
4. 输入内容后，提交
5. 报错，提示 View 字段缺少默认值

打开数据库，看到View字段是缺少默认值的。

另外，如果在后台，卸载然后重新安装这个应用插件，问题就解决了。

![1](https://user-images.githubusercontent.com/6181442/54882369-428a5880-4e94-11e9-9c39-cb9ea3814392.PNG)

**Comment by jianyan74** [comment]
ok 历史遗留问题
