### ISSUE TITLE
执行这一步php ./yii migrate/up

### ISSUE THREAD

**Issue by Baiqu** [jianyan74/rageframe2#80]
PHP Warning:  require(/www/wwwroot/mall.baisoft.co/rageframe2/vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/mall.baisoft.co/rageframe2/yii on line 10

Warning: require(/www/wwwroot/mall.baisoft.co/rageframe2/vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/mall.baisoft.co/rageframe2/yii on line 10
PHP Fatal error:  require(): Failed opening required '/www/wwwroot/mall.baisoft.co/rageframe2/vendor/autoload.php' (include_path='.:/www/server/php/55/lib/php') in /www/wwwroot/mall.baisoft.co/rageframe2/y ii on line 10

Fatal error: require(): Failed opening required '/www/wwwroot/mall.baisoft.co/rageframe2/vendor/autoload.php' (include_path='.:/www/server/php/55/lib/php') in /www/wwwroot/mall.baisoft.co/rageframe2/yii on  line 10

发现没有这个目录：vendor

**Comment by jianyan74** [comment]
因为你安装文档第三步安装依赖没有执行成功，php composer.phar install

**Comment by Baiqu** [comment]
php composer.phar install   这个后来安装了，也不行，重装了3次，等会再仔细重装一次看。系统是Ubuntu 18    PHP 7.3  装的bt.cn

**Comment by jianyan74** [comment]
执行了不一定可以成功，注意看报错，然后解决报错

**Comment by Baiqu** [comment]
嗯，確實，今天又刪除了，重裝了一次，終於成功了。還在研究中，謝謝。

**Comment by jianyan74** [comment]
ok
