### ISSUE TITLE
你好，非常感謝你提供的代碼，有以下問題

### ISSUE THREAD

**Issue by Baiqu** [jianyan74/rageframe2#81]
1、後臺有沒有幫助說明
2、找不到說明，研究了一下，裝好了商戶，打開商戶註冊，但註冊進來的用戶，是未授權的狀態，如果在後臺裏增加用戶，就可以選擇角色。（這一點，也不確定是不是後臺創建的角色，如果沒有角色就是不行的，但如果沒有角色，是否讓註冊）
3、後臺也沒有對用戶，設定角色的功能。
4、商戶的用戶登陸進來，沒有微商城的入口，找到商家配置裏有，但不知道如何增加微商城的功能，同時也不知道，是不是每個商戶增加的商品是屬該商戶自己所有。
暫時發現這時問題，希望這個系統能用進來。

**Comment by jianyan74** [comment]
1、本地文档就是帮助说明

**Comment by jianyan74** [comment]
2、没有角色可以被注册，可以到商户自己添加下角色，每个角色都是独立于商户的

**Comment by jianyan74** [comment]
3、微商城暂时未开放对商户端的用户显示，有这个需求可以自己二开，做过底层优化，每个商户增加的商品是自己所有
