### ISSUE TITLE
可否修复一下上传控件common\widgets\webuploader\Files手机端点击问题

### ISSUE THREAD

**Issue by wblbird** [jianyan74/rageframe2#83]
在多数手机浏览器都正常，电脑浏览器手机模式有问题，在微信钉钉里，点击选文件或点选删除再点选就不正常了，常常是点击容器外围边缘才弹出文件选择框，点选文件上传后，右上角也没显示删除图标，要长按才显示

**Comment by jianyan74** [comment]
后面优化，你也可以自己优化了提pr

**Comment by reiyi2007** [comment]
是拖动插件的BUG吧, 把排序的功能关掉就好了_(:з」∠)_

**Comment by jianyan74** [comment]
修复了
