### ISSUE TITLE
后台改价后不能拉起支付的BUG

### ISSUE THREAD

**Issue by wpstqe** [jianyan74/rageframe2#87]
修改common/models/forms/payform.php的getConfig方法中设置out_trade_no的位置。
改价后如果不更改out_trade_no，申请到上游支付渠道时会比对支付金额。如果金额不对的情况下，会拒绝请求，所以每次请求支付都需要生成新的out_trade_no

**Comment by jianyan74** [comment]
好的

**Comment by jianyan74** [comment]
这个是出现在，已经提交了支付又取消了，然后再去改价进行支付的情况下是么？
