### ISSUE TITLE
插件安装建议

### ISSUE THREAD

**Issue by SwankyTigerYY** [jianyan74/rageframe2#89]
后台安装插件超时，还得人为去修改apache或者nginx，插件安装的等待也不友好

**Comment by SwankyTigerYY** [comment]
安装你的TinyShop项目发现的，缺表，其实是因为默认限制30s，没执行完数据迁移

**Comment by jianyan74** [comment]
这个就很尴尬了，默认30s

**Comment by SwankyTigerYY** [comment]
如果方便的话希望能加上ini_set("max_execution_time",时间);或者“set_time_out”。当然我没来得及看源码，我只是建议。

**Comment by SwankyTigerYY** [comment]
十分感谢，此开源项目非常棒

**Comment by jianyan74** [comment]
ok

**Comment by jianyan74** [comment]
时间改好了

**Comment by SwankyTigerYY** [comment]
感谢~！！
