### ISSUE TITLE
支付回调的demo和文档里写的不一致，我测了两种方式都不能正常执行代码

### ISSUE THREAD

**Issue by codetown** [jianyan74/rageframe2#9]
$response = Yii::$app->wechat->payment->handlePaidNotify(function ($message, $fail) {
    // 你的逻辑
    return true;
    // 或者错误消息
    $fail('Order not exists.');
});
$response->send();

$response = Yii::$app->pay->wechat->notify();
//var_dump($response);exit;
        if ($response->isPaid())//一直返回false，支付是成功的
        {
            //pay success 注意微信会发二次消息过来 需要判断是通知还是回调
            var_dump($response->getRequestData());

            // 成功通知
            return PayHelper::notifyWechatSuccess();
        }
        else
        {
            // 失败通知
            return PayHelper::notifyWechatFail();
        }

**Comment by jianyan74** [comment]
多看看easywechat文档 在看下你自己的请求是否过来了

**Comment by codetown** [comment]
> 多看看easywechat文档 在看下你自己的请求是否过来了
自己写回调逻辑了，能够接受到微信回调返回的数据信息。
建议提供统一的微信回调处理方法，多种写法都包含显得太混乱。
而且两种写法我确实都没有调通，但是使用微信自己的demo就可以。

**Comment by jianyan74** [comment]
微信的直接用easywechat的回调方式即可，人家那么大的下载量不会出现这种明显的bug的
