### ISSUE TITLE
执行 php composer.phar install时卡死

### ISSUE THREAD

**Issue by allenE1** [jianyan74/rageframe2#91]
当我按照文档git clone下载完项目，进入项目目录，命令行执行php composer.phar install，命令行一个小时都没有变化，只有两行提示语 Loading composer repositories with package information
            Updating dependencies (including require-dev)

我百度试了很多方法都没啥用，如 更新composer，清理composer缓存，更换composer源...

请问该如何才能快速的下载项目所依赖的包呢？

**Comment by jianyan74** [comment]
用阿里的源，或者直接加群，群里有完整包

**Comment by September999999999** [comment]
`php -d memory_limit=-1  composer install  -vvvv`
执行这条命令,看下具体报错信息
