### ISSUE TITLE
如果后台能做成前后端分离用vue就完美了

### ISSUE THREAD

**Issue by xhun2015** [jianyan74/rageframe2#93]
一直想找一个基础功能完善，带商城，多商户的开源框架，无疑rageframe就是最好选择，但是，不是前后端分离，vue写前端以数据驱动界面，开发效率会更快速，再加上app前端使用uniapp，也是vue相关技术栈，这样技术栈可以统一。但是我初步分析了下，如果使用vue,yii的一些特性就没法使用了，最关键的是插件的前端，如何才能实现安装与卸载。作者是否有好的建议呢？

**Comment by jianyan74** [comment]
不考虑后台前后分离，用vue只适合自己公司玩的项目，非前后分离可玩性就大了，任何人都可以参与
