### ISSUE TITLE
关于微信公众号插件获取用户列表的问题

### ISSUE THREAD

**Issue by uutan** [jianyan74/rageframe2#97]
公众号可通过本接口来获取帐号的关注者列表，关注者列表由一串OpenID（加密后的微信号，每个用户对每个公众号的OpenID是唯一的）组成。一次拉取调用最多拉取10000个关注者的OpenID，可以通过多次拉取的方式来满足需求。

目前设计没有考虑到, 单次拉取只能是10000个关注者, 当关注者超过2万个时, 后面一个关注者数据无法获取.

**Comment by uutan** [comment]
公众号关注者列表接口描述地址如下:
https://developers.weixin.qq.com/doc/offiaccount/User_Management/Getting_a_User_List.html

**Comment by jianyan74** [comment]
已修复

**Comment by uutan** [comment]
这效率真高.!!!
