### ISSUE TITLE
执行`php ./yii migrate/up`报错

### ISSUE THREAD

**Issue by wujiops** [jianyan74/rageframe2#99]
PHP Warning:  require(/opt/rageframe2/vendor/autoload.php): failed to open stream: No such file or directory in /opt/rageframe2/yii on line 10
PHP Fatal error:  require(): Failed opening required '/opt/rageframe2/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/rageframe2/yii on line 10

**Comment by jianyan74** [comment]
依赖没有安装
